//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB5_SERVICE_UI.NumConv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="NumConv.NumberConversionSoapType")]
    public interface NumberConversionSoapType {
        
        // CODEGEN: Контракт генерации сообщений с именем NumberToWordsResult из пространства имен http://www.dataaccess.com/webservicesserver/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LAB5_SERVICE_UI.NumConv.NumberToWordsResponse NumberToWords(LAB5_SERVICE_UI.NumConv.NumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToWordsResponse> NumberToWordsAsync(LAB5_SERVICE_UI.NumConv.NumberToWordsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем NumberToDollarsResult из пространства имен http://www.dataaccess.com/webservicesserver/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse NumberToDollars(LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse> NumberToDollarsAsync(LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public LAB5_SERVICE_UI.NumConv.NumberToWordsRequestBody Body;
        
        public NumberToWordsRequest() {
        }
        
        public NumberToWordsRequest(LAB5_SERVICE_UI.NumConv.NumberToWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ubiNum;
        
        public NumberToWordsRequestBody() {
        }
        
        public NumberToWordsRequestBody(ulong ubiNum) {
            this.ubiNum = ubiNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public LAB5_SERVICE_UI.NumConv.NumberToWordsResponseBody Body;
        
        public NumberToWordsResponse() {
        }
        
        public NumberToWordsResponse(LAB5_SERVICE_UI.NumConv.NumberToWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToWordsResult;
        
        public NumberToWordsResponseBody() {
        }
        
        public NumberToWordsResponseBody(string NumberToWordsResult) {
            this.NumberToWordsResult = NumberToWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public LAB5_SERVICE_UI.NumConv.NumberToDollarsRequestBody Body;
        
        public NumberToDollarsRequest() {
        }
        
        public NumberToDollarsRequest(LAB5_SERVICE_UI.NumConv.NumberToDollarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal dNum;
        
        public NumberToDollarsRequestBody() {
        }
        
        public NumberToDollarsRequestBody(decimal dNum) {
            this.dNum = dNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public LAB5_SERVICE_UI.NumConv.NumberToDollarsResponseBody Body;
        
        public NumberToDollarsResponse() {
        }
        
        public NumberToDollarsResponse(LAB5_SERVICE_UI.NumConv.NumberToDollarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToDollarsResult;
        
        public NumberToDollarsResponseBody() {
        }
        
        public NumberToDollarsResponseBody(string NumberToDollarsResult) {
            this.NumberToDollarsResult = NumberToDollarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumberConversionSoapTypeChannel : LAB5_SERVICE_UI.NumConv.NumberConversionSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<LAB5_SERVICE_UI.NumConv.NumberConversionSoapType>, LAB5_SERVICE_UI.NumConv.NumberConversionSoapType {
        
        public NumberConversionSoapTypeClient() {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAB5_SERVICE_UI.NumConv.NumberToWordsResponse LAB5_SERVICE_UI.NumConv.NumberConversionSoapType.NumberToWords(LAB5_SERVICE_UI.NumConv.NumberToWordsRequest request) {
            return base.Channel.NumberToWords(request);
        }
        
        public string NumberToWords(ulong ubiNum) {
            LAB5_SERVICE_UI.NumConv.NumberToWordsRequest inValue = new LAB5_SERVICE_UI.NumConv.NumberToWordsRequest();
            inValue.Body = new LAB5_SERVICE_UI.NumConv.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            LAB5_SERVICE_UI.NumConv.NumberToWordsResponse retVal = ((LAB5_SERVICE_UI.NumConv.NumberConversionSoapType)(this)).NumberToWords(inValue);
            return retVal.Body.NumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToWordsResponse> LAB5_SERVICE_UI.NumConv.NumberConversionSoapType.NumberToWordsAsync(LAB5_SERVICE_UI.NumConv.NumberToWordsRequest request) {
            return base.Channel.NumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum) {
            LAB5_SERVICE_UI.NumConv.NumberToWordsRequest inValue = new LAB5_SERVICE_UI.NumConv.NumberToWordsRequest();
            inValue.Body = new LAB5_SERVICE_UI.NumConv.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            return ((LAB5_SERVICE_UI.NumConv.NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse LAB5_SERVICE_UI.NumConv.NumberConversionSoapType.NumberToDollars(LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollars(request);
        }
        
        public string NumberToDollars(decimal dNum) {
            LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest inValue = new LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest();
            inValue.Body = new LAB5_SERVICE_UI.NumConv.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse retVal = ((LAB5_SERVICE_UI.NumConv.NumberConversionSoapType)(this)).NumberToDollars(inValue);
            return retVal.Body.NumberToDollarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse> LAB5_SERVICE_UI.NumConv.NumberConversionSoapType.NumberToDollarsAsync(LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAB5_SERVICE_UI.NumConv.NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum) {
            LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest inValue = new LAB5_SERVICE_UI.NumConv.NumberToDollarsRequest();
            inValue.Body = new LAB5_SERVICE_UI.NumConv.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            return ((LAB5_SERVICE_UI.NumConv.NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
        }
    }
}
