//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB5_SERVICE_UI.SpellService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://speller.yandex.net/services/spellservice", ConfigurationName="SpellService1.SpellServiceSoap")]
    public interface SpellServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CheckTextRequest) сообщения checkTextRequest не соответствует значению по умолчанию (checkText).
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LAB5_SERVICE_UI.SpellService1.checkTextResponse checkText(LAB5_SERVICE_UI.SpellService1.checkTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkText", ReplyAction="*")]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextResponse> checkTextAsync(LAB5_SERVICE_UI.SpellService1.checkTextRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CheckTextsRequest) сообщения checkTextsRequest не соответствует значению по умолчанию (checkTexts).
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkTexts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LAB5_SERVICE_UI.SpellService1.checkTextsResponse checkTexts(LAB5_SERVICE_UI.SpellService1.checkTextsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://speller.yandex.net/services/spellservice/checkTexts", ReplyAction="*")]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextsResponse> checkTextsAsync(LAB5_SERVICE_UI.SpellService1.checkTextsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://speller.yandex.net/services/spellservice")]
    public partial class SpellError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string wordField;
        
        private string[] sField;
        
        private int codeField;
        
        private int posField;
        
        private int rowField;
        
        private int colField;
        
        private int lenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                this.wordField = value;
                this.RaisePropertyChanged("word");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("s", Order=1)]
        public string[] s {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
                this.RaisePropertyChanged("s");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
                this.RaisePropertyChanged("pos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int col {
            get {
                return this.colField;
            }
            set {
                this.colField = value;
                this.RaisePropertyChanged("col");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int len {
            get {
                return this.lenField;
            }
            set {
                this.lenField = value;
                this.RaisePropertyChanged("len");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextRequest", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string format;
        
        public checkTextRequest() {
        }
        
        public checkTextRequest(string text, string lang, int options, string format) {
            this.text = text;
            this.lang = lang;
            this.options = options;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextResponse", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public LAB5_SERVICE_UI.SpellService1.SpellError[] SpellResult;
        
        public checkTextResponse() {
        }
        
        public checkTextResponse(LAB5_SERVICE_UI.SpellService1.SpellError[] SpellResult) {
            this.SpellResult = SpellResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextsRequest", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("text")]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=1)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=2)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int options;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=3)]
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string format;
        
        public checkTextsRequest() {
        }
        
        public checkTextsRequest(string[] text, string lang, int options, string format) {
            this.text = text;
            this.lang = lang;
            this.options = options;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckTextsResponse", WrapperNamespace="http://speller.yandex.net/services/spellservice", IsWrapped=true)]
    public partial class checkTextsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://speller.yandex.net/services/spellservice", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SpellResult", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false, NestingLevel=1)]
        public LAB5_SERVICE_UI.SpellService1.SpellError[][] ArrayOfSpellResult;
        
        public checkTextsResponse() {
        }
        
        public checkTextsResponse(LAB5_SERVICE_UI.SpellService1.SpellError[][] ArrayOfSpellResult) {
            this.ArrayOfSpellResult = ArrayOfSpellResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpellServiceSoapChannel : LAB5_SERVICE_UI.SpellService1.SpellServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpellServiceSoapClient : System.ServiceModel.ClientBase<LAB5_SERVICE_UI.SpellService1.SpellServiceSoap>, LAB5_SERVICE_UI.SpellService1.SpellServiceSoap {
        
        public SpellServiceSoapClient() {
        }
        
        public SpellServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpellServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpellServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAB5_SERVICE_UI.SpellService1.checkTextResponse LAB5_SERVICE_UI.SpellService1.SpellServiceSoap.checkText(LAB5_SERVICE_UI.SpellService1.checkTextRequest request) {
            return base.Channel.checkText(request);
        }
        
        public LAB5_SERVICE_UI.SpellService1.SpellError[] checkText(string text, string lang, int options, string format) {
            LAB5_SERVICE_UI.SpellService1.checkTextRequest inValue = new LAB5_SERVICE_UI.SpellService1.checkTextRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            LAB5_SERVICE_UI.SpellService1.checkTextResponse retVal = ((LAB5_SERVICE_UI.SpellService1.SpellServiceSoap)(this)).checkText(inValue);
            return retVal.SpellResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextResponse> LAB5_SERVICE_UI.SpellService1.SpellServiceSoap.checkTextAsync(LAB5_SERVICE_UI.SpellService1.checkTextRequest request) {
            return base.Channel.checkTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextResponse> checkTextAsync(string text, string lang, int options, string format) {
            LAB5_SERVICE_UI.SpellService1.checkTextRequest inValue = new LAB5_SERVICE_UI.SpellService1.checkTextRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            return ((LAB5_SERVICE_UI.SpellService1.SpellServiceSoap)(this)).checkTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LAB5_SERVICE_UI.SpellService1.checkTextsResponse LAB5_SERVICE_UI.SpellService1.SpellServiceSoap.checkTexts(LAB5_SERVICE_UI.SpellService1.checkTextsRequest request) {
            return base.Channel.checkTexts(request);
        }
        
        public LAB5_SERVICE_UI.SpellService1.SpellError[][] checkTexts(string[] text, string lang, int options, string format) {
            LAB5_SERVICE_UI.SpellService1.checkTextsRequest inValue = new LAB5_SERVICE_UI.SpellService1.checkTextsRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            LAB5_SERVICE_UI.SpellService1.checkTextsResponse retVal = ((LAB5_SERVICE_UI.SpellService1.SpellServiceSoap)(this)).checkTexts(inValue);
            return retVal.ArrayOfSpellResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextsResponse> LAB5_SERVICE_UI.SpellService1.SpellServiceSoap.checkTextsAsync(LAB5_SERVICE_UI.SpellService1.checkTextsRequest request) {
            return base.Channel.checkTextsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LAB5_SERVICE_UI.SpellService1.checkTextsResponse> checkTextsAsync(string[] text, string lang, int options, string format) {
            LAB5_SERVICE_UI.SpellService1.checkTextsRequest inValue = new LAB5_SERVICE_UI.SpellService1.checkTextsRequest();
            inValue.text = text;
            inValue.lang = lang;
            inValue.options = options;
            inValue.format = format;
            return ((LAB5_SERVICE_UI.SpellService1.SpellServiceSoap)(this)).checkTextsAsync(inValue);
        }
    }
}
